version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Load init.sql saat pertama kali container berjalan

  backend:
    build: ./server
    container_name: backend-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./client
    container_name: frontend-app
    restart: always
    depends_on:
      - backend
    env_file:
      - ./client/.env
    ports:
      - "80:80"

volumes:
  mysql_data:
